### ISSUE TITLE
Widget Not Compatible with Google Now Launcher

### ISSUE THREAD

**Issue by commandersouth** [drmercer/Ponderizer#38]
Cannot add widget using Google Now Launcher

**Comment by commandersouth** [comment]
Very odd. Reboot resolved issue. When opening other launcher widget showed up before reboot.  Took reboot to show up in Now Launcher.

**Comment by drmercer** [comment]
I have had a complaint of this issue in the past (although not specifically with Google Now Launcher, to my knowledge), and I'm not sure what causes it. It does seem to be a problem that a number of people have, although I don't think I've experienced it myself. Also, I don't think it's a fault with GNL in particular, because I use GNL on my main development device.

http://forums.androidcentral.com/droid-razr-maxx/187678-widgets-list-not-updating-immediately.html
http://androidforums.com/threads/widget-does-not-appear-after-installation.575877/

By some sources it appears that this is by design, because Android does not remove an app from the "stopped" state until the app is manually started by the user:
http://stackoverflow.com/a/8700787/1124748
https://groups.google.com/forum/#!topic/android-developers/bvlk3EOV6Xk
